create table REP_EXPLAIN_PLANS( STATEMENT_ID    VARCHAR2(1000), PLAN_ID VARCHAR2(400), TIMESTAMP        DATE, REMARKS   VARCHAR2(1000), OPERATION       VARCHAR2(1000), OPTIONS VARCHAR2(1000), OBJECT_NODE     VARCHAR2(1000), OBJECT_OWNER    VARCHAR2(1000), OBJECT_NAME     VARCHAR2(1000), OBJECT_INSTANCE NUMBER(38), OBJECT_TYPE VARCHAR2(1000), OPTIMIZER       VARCHAR2(1000), SEARCH_COLUMNS  NUMBER, ID      NUMBER(38)      , PARENT_ID     NUMBER(38), DEPTH number(38), POSITION  NUMBER(38), COST        NUMBER(38), CARDINALITY NUMBER(38), BYTES       NUMBER(38), OTHER_TAG  VARCHAR2(1000), PARTITION_START  VARCHAR2(1000), PARTITION_STOP  VARCHAR2(1000), PARTITION_ID    NUMBER(38), DISTRIBUTION        VARCHAR2(1000), CPU_COST        NUMBER(38), IO_COST     NUMBER(38), TEMP_SPACE  NUMBER(38), ACCESS_PREDICATES   VARCHAR2(4000), FILTER_PREDICATES               VARCHAR2(4000), TIME    NUMBER(38), TPC_TRANSACTION_NAME varchar2(20), STATEMENT_HASH_SUM varchar2(4000), BENCHMARK_ITERATION varchar2(2), GATHERED_STATS varchar2(5) )tablespace users;
--
select   pt.STATEMENT_ID
		,pt.PLAN_ID
		,pt.TIMESTAMP
		,pt.REMARKS
		,pt.OPERATION
		,pt.OPTIONS
		,pt.OBJECT_NODE
		,pt.OBJECT_OWNER
		,pt.OBJECT_NAME
		,pt.OBJECT_INSTANCE
		,pt.OBJECT_TYPE
		,pt.OPTIMIZER
		,pt.SEARCH_COLUMNS
		,pt.ID
		,pt.PARENT_ID
		,pt.depth
		,pt.POSITION
		,pt.COST
		,pt.CARDINALITY
		,pt.BYTES
		,pt.OTHER_TAG
		,pt.PARTITION_START
		,pt.PARTITION_STOP
		,pt.PARTITION_ID
		,pt.DISTRIBUTION
		,pt.CPU_COST
		,pt.IO_COST
		,pt.TEMP_SPACE
		,pt.ACCESS_PREDICATES
		,pt.FILTER_PREDICATES
		,pt.TIME
		,'transaction_name',
		'md5_sum',
		'iteration_run',
		'gathered_stats'
from plan_table pt
where plan_id = (
  select max(plan_id)
  from plan_table
  where to_date(to_char(timestamp,'MM/DD/YYYY'),'MM/DD/YYYY') = to_date(to_char(sysdate,'MM/DD/YYYY'),'MM/DD/YYYY')
)
order by id;