/*
TPC-DS Schema Enhancement - Adding Indexes
*/                                        
-- Table store_sales
create index ss_sold_date_sk_index on store_sales (ss_sold_date_sk) parallel 30;
create index ss_sold_time_sk_index on store_sales (ss_sold_time_sk) parallel 30;
create index ss_item_sk_index on store_sales (ss_item_sk) parallel 30;
create index ss_customer_sk_index on store_sales (ss_customer_sk) parallel 30;
create index ss_cdemo_sk_index on store_sales (ss_cdemo_sk) parallel 30;
create index ss_hdemo_sk_index on store_sales (ss_hdemo_sk) parallel 30;
create index ss_addr_sk_index on store_sales (ss_addr_sk) parallel 30;
create index ss_store_sk_index on store_sales (ss_store_sk) parallel 30;
create index ss_promo_sk_index on store_sales (ss_promo_sk) parallel 30;
create index ss_ticket_number_index on store_sales (ss_ticket_number) parallel 30;
-- Table store_returns
create index sr_returned_date_sk_index on store_returns (sr_returned_date_sk) parallel 30;
create index sr_return_time_sk_index on store_returns (sr_return_time_sk) parallel 30;
create index sr_item_sk on store_returns (sr_item_sk) parallel 30;
create index sr_customer_sk_index on store_returns (sr_customer_sk) parallel 30;
create index sr_cdemo_sk_index on store_returns (sr_cdemo_sk) parallel 30;
create index sr_hdemo_sk_index on store_returns (sr_hdemo_sk) parallel 30;
create index sr_addr_sk_index on store_returns (sr_addr_sk) parallel 30;
create index sr_store_sk_index on store_returns (sr_store_sk) parallel 30;
create index sr_reason_sk_index on store_returns (sr_reason_sk) parallel 30;
create index sr_ticket_number_index on store_returns (sr_ticket_number) parallel 30;
-- Table catalog_sales
create index cs_sold_date_sk_index on catalog_sales (cs_sold_date_sk) parallel 30;
create index cs_sold_time_sk_index on catalog_sales (cs_sold_time_sk) parallel 30;
create index cs_ship_date_sk_index on catalog_sales (cs_ship_date_sk) parallel 30;
create index cs_bill_customer_sk_index on catalog_sales (cs_bill_customer_sk) parallel 30;
create index cs_bill_cdemo_sk_index on catalog_sales (cs_bill_cdemo_sk) parallel 30;
create index cs_bill_hdemo_sk_index on catalog_sales (cs_bill_hdemo_sk) parallel 30;
create index cs_bill_addr_sk_index on catalog_sales (cs_bill_addr_sk) parallel 30;
create index cs_ship_customer_sk_index on catalog_sales (cs_ship_customer_sk) parallel 30;
create index cs_ship_cdemo_sk_index on catalog_sales (cs_ship_cdemo_sk) parallel 30;
create index cs_ship_hdemo_sk_index on catalog_sales (cs_ship_hdemo_sk) parallel 30;
create index cs_ship_addr_sk_index on catalog_sales (cs_ship_addr_sk) parallel 30;
create index cs_call_center_sk_index on catalog_sales (cs_call_center_sk) parallel 30;
create index cs_catalog_page_sk_index on catalog_sales (cs_catalog_page_sk) parallel 30;
create index cs_ship_mode_sk_index on catalog_sales (cs_ship_mode_sk) parallel 30;
create index cs_warehouse_sk_index on catalog_sales (cs_warehouse_sk) parallel 30;
create index cs_item_sk_index on catalog_sales (cs_item_sk) parallel 30;
create index cs_promo_sk_index on catalog_sales (cs_promo_sk) parallel 30;
create index cs_order_number_index on catalog_sales (cs_order_number) parallel 30;
-- Table catalog_returns
create index cr_returned_date_sk_index on catalog_returns (cr_returned_date_sk) parallel 30;
create index cr_returned_time_sk_index on catalog_returns (cr_returned_time_sk) parallel 30;
create index cr_item_sk_index on catalog_returns (cr_item_sk) parallel 30;
create index cr_refunded_customer_sk_index on catalog_returns (cr_refunded_customer_sk) parallel 30;
create index cr_refunded_cdemo_sk_index on catalog_returns (cr_refunded_cdemo_sk) parallel 30;
create index cr_refunded_hdemo_sk_index on catalog_returns (cr_refunded_hdemo_sk) parallel 30;
create index cr_refunded_addr_sk_index on catalog_returns (cr_refunded_addr_sk) parallel 30;
create index cr_returning_customer_sk_index on catalog_returns (cr_returning_customer_sk) parallel 30;
create index cr_returning_cdemo_sk_index on catalog_returns (cr_returning_cdemo_sk) parallel 30;
create index cr_returning_hdemo_sk_index on catalog_returns (cr_returning_hdemo_sk) parallel 30;
create index cr_returning_addr_sk_index on catalog_returns (cr_returning_addr_sk) parallel 30;
create index cr_call_center_sk_index on catalog_returns (cr_call_center_sk) parallel 30;
create index cr_catalog_page_sk_index on catalog_returns (cr_catalog_page_sk) parallel 30;
create index cr_ship_mode_sk_index on catalog_returns (cr_ship_mode_sk) parallel 30;
create index cr_warehouse_sk_index on catalog_returns (cr_warehouse_sk) parallel 30;
create index cr_reason_sk_index on catalog_returns (cr_reason_sk) parallel 30;
create index cr_order_number_index on catalog_returns (cr_order_number) parallel 30;
-- Table web_sales
create index ws_sold_date_sk_index on web_sales (ws_sold_date_sk) parallel 30;
create index ws_sold_time_sk_index on web_sales (ws_sold_time_sk) parallel 30;
create index ws_ship_date_sk_index on web_sales (ws_ship_date_sk) parallel 30;
create index ws_item_sk_index on web_sales (ws_item_sk) parallel 30;
create index ws_bill_customer_sk_index on web_sales (ws_bill_customer_sk) parallel 30;
create index ws_bill_cdemo_sk_index on web_sales (ws_bill_cdemo_sk) parallel 30;
create index ws_bill_hdemo_sk_index on web_sales (ws_bill_hdemo_sk) parallel 30;
create index ws_bill_addr_sk_index on web_sales (ws_bill_addr_sk) parallel 30;
create index ws_ship_customer_sk_index on web_sales (ws_ship_customer_sk) parallel 30;
create index ws_ship_cdemo_sk_index on web_sales (ws_ship_cdemo_sk) parallel 30;
create index ws_ship_hdemo_sk_index on web_sales (ws_ship_hdemo_sk) parallel 30;
create index ws_ship_addr_sk_index on web_sales (ws_ship_addr_sk) parallel 30;
create index ws_web_page_sk_index on web_sales (ws_web_page_sk) parallel 30;
create index ws_web_site_sk_index on web_sales (ws_web_site_sk) parallel 30;
create index ws_ship_mode_sk_index on web_sales (ws_ship_mode_sk) parallel 30;
create index ws_warehouse_sk_index on web_sales (ws_warehouse_sk) parallel 30;
create index ws_promo_sk_index on web_sales (ws_promo_sk) parallel 30;
create index ws_order_number_index on web_sales (ws_order_number) parallel 30;
-- Table web_returns
create index wr_returned_date_sk_index on web_returns (wr_returned_date_sk) parallel 30;
create index wr_returned_time_sk_index on web_returns (wr_returned_time_sk) parallel 30;
create index wr_item_sk_index on web_returns (wr_item_sk) parallel 30;
create index wr_refunded_customer_sk_index on web_returns (wr_refunded_customer_sk) parallel 30;
create index wr_refunded_cdemo_sk_index on web_returns (wr_refunded_cdemo_sk) parallel 30;
create index wr_refunded_hdemo_sk_index on web_returns (wr_refunded_hdemo_sk) parallel 30;
create index wr_refunded_addr_sk_index on web_returns (wr_refunded_addr_sk) parallel 30;
create index wr_returning_customer_sk_index on web_returns (wr_returning_customer_sk) parallel 30;
create index wr_returning_cdemo_sk_index on web_returns (wr_returning_cdemo_sk) parallel 30;
create index wr_returning_hdemo_sk_index on web_returns (wr_returning_hdemo_sk) parallel 30;
create index wr_returning_addr_sk_index on web_returns (wr_returning_addr_sk) parallel 30;
create index wr_web_page_sk_index on web_returns (wr_web_page_sk) parallel 30;
create index wr_reason_sk_index on web_returns (wr_reason_sk) parallel 30;
create index wr_order_number_index on web_returns (wr_order_number) parallel 30;
-- Table inventory
create index inv_item_sk_index on inventory (inv_item_sk) parallel 30;
create index inv_date_sk_index on inventory (inv_date_sk) parallel 30;
create index inv_warehouse_sk_index on inventory (inv_warehouse_sk) parallel 30;
-- Table catalog_page
create index cp_start_date_sk_index on catalog_page (cp_start_date_sk) parallel 30;
create index cp_end_date_sk_index on catalog_page (cp_end_date_sk) parallel 30;
-- Table web_page
create index wp_creation_date_sk_index on web_page (wp_creation_date_sk) parallel 30;
create index wp_access_date_sk_index on web_page (wp_access_date_sk) parallel 30;
create index wp_customer_sk_index on web_page (wp_customer_sk) parallel 30;
-- Table customer
create index c_current_cdemo_sk_index on customer (c_current_cdemo_sk) parallel 30;
create index c_current_hdemo_sk_index on customer (c_current_hdemo_sk) parallel 30;
create index c_current_addr_sk_index on customer (c_current_addr_sk) parallel 30;
create index c_first_shipto_date_sk_index on customer (c_first_shipto_date_sk) parallel 30;
create index c_first_sales_date_sk_index on customer (c_first_sales_date_sk) parallel 30;
--
alter index SS_SOLD_DATE_SK_INDEX noparallel;
alter index SS_SOLD_TIME_SK_INDEX noparallel;
alter index SS_ITEM_SK_INDEX noparallel;
alter index SS_CUSTOMER_SK_INDEX noparallel;
alter index SS_CDEMO_SK_INDEX noparallel;
alter index SS_HDEMO_SK_INDEX noparallel;
alter index SS_ADDR_SK_INDEX noparallel;
alter index SS_STORE_SK_INDEX noparallel;
alter index SS_PROMO_SK_INDEX noparallel;
alter index SS_TICKET_NUMBER_INDEX noparallel;
alter index CS_SOLD_DATE_SK_INDEX noparallel;
alter index CS_SOLD_TIME_SK_INDEX noparallel;
alter index CS_SHIP_DATE_SK_INDEX noparallel;
alter index CS_BILL_CUSTOMER_SK_INDEX noparallel;
alter index CS_BILL_CDEMO_SK_INDEX noparallel;
alter index CS_BILL_HDEMO_SK_INDEX noparallel;
alter index CS_BILL_ADDR_SK_INDEX noparallel;
alter index CS_SHIP_CUSTOMER_SK_INDEX noparallel;
alter index CS_SHIP_CDEMO_SK_INDEX noparallel;
alter index CS_SHIP_HDEMO_SK_INDEX noparallel;
alter index CS_SHIP_ADDR_SK_INDEX noparallel;
alter index CS_CALL_CENTER_SK_INDEX noparallel;
alter index CS_CATALOG_PAGE_SK_INDEX noparallel;
alter index CS_SHIP_MODE_SK_INDEX noparallel;
alter index CS_WAREHOUSE_SK_INDEX noparallel;
alter index CS_ITEM_SK_INDEX noparallel;
alter index CS_PROMO_SK_INDEX noparallel;
alter index CS_ORDER_NUMBER_INDEX noparallel;
alter index WS_SOLD_DATE_SK_INDEX noparallel;
alter index WS_SOLD_TIME_SK_INDEX noparallel;
alter index WS_SHIP_DATE_SK_INDEX noparallel;
alter index WS_ITEM_SK_INDEX noparallel;
alter index WS_BILL_CUSTOMER_SK_INDEX noparallel;
alter index WS_BILL_CDEMO_SK_INDEX noparallel;
alter index WS_BILL_HDEMO_SK_INDEX noparallel;
alter index WS_BILL_ADDR_SK_INDEX noparallel;
alter index WS_SHIP_CUSTOMER_SK_INDEX noparallel;
alter index WS_SHIP_CDEMO_SK_INDEX noparallel;
alter index WS_SHIP_HDEMO_SK_INDEX noparallel;
alter index WS_SHIP_ADDR_SK_INDEX noparallel;
alter index WS_WEB_PAGE_SK_INDEX noparallel;
alter index WS_WEB_SITE_SK_INDEX noparallel;
alter index WS_SHIP_MODE_SK_INDEX noparallel;
alter index WS_WAREHOUSE_SK_INDEX noparallel;
alter index WS_PROMO_SK_INDEX noparallel;
alter index WS_ORDER_NUMBER_INDEX noparallel;
alter index WR_RETURNED_DATE_SK_INDEX noparallel;
alter index WR_RETURNED_TIME_SK_INDEX noparallel;
alter index WR_ITEM_SK_INDEX noparallel;
alter index WR_REFUNDED_CUSTOMER_SK_INDEX noparallel;
alter index WR_REFUNDED_CDEMO_SK_INDEX noparallel;
alter index WR_REFUNDED_HDEMO_SK_INDEX noparallel;
alter index WR_REFUNDED_ADDR_SK_INDEX noparallel;
alter index WR_RETURNING_CUSTOMER_SK_INDEX noparallel;
alter index WR_RETURNING_CDEMO_SK_INDEX noparallel;
alter index WR_RETURNING_HDEMO_SK_INDEX noparallel;
alter index WR_RETURNING_ADDR_SK_INDEX noparallel;
alter index WR_WEB_PAGE_SK_INDEX noparallel;
alter index WR_REASON_SK_INDEX noparallel;
alter index WR_ORDER_NUMBER_INDEX noparallel;
alter index CR_RETURNED_DATE_SK_INDEX noparallel;
alter index CR_RETURNED_TIME_SK_INDEX noparallel;
alter index CR_ITEM_SK_INDEX noparallel;
alter index CR_REFUNDED_CUSTOMER_SK_INDEX noparallel;
alter index CR_REFUNDED_CDEMO_SK_INDEX noparallel;
alter index CR_REFUNDED_HDEMO_SK_INDEX noparallel;
alter index CR_REFUNDED_ADDR_SK_INDEX noparallel;
alter index CR_RETURNING_CUSTOMER_SK_INDEX noparallel;
alter index CR_RETURNING_CDEMO_SK_INDEX noparallel;
alter index CR_RETURNING_HDEMO_SK_INDEX noparallel;
alter index CR_RETURNING_ADDR_SK_INDEX noparallel;
alter index CR_CALL_CENTER_SK_INDEX noparallel;
alter index CR_CATALOG_PAGE_SK_INDEX noparallel;
alter index CR_SHIP_MODE_SK_INDEX noparallel;
alter index CR_WAREHOUSE_SK_INDEX noparallel;
alter index CR_REASON_SK_INDEX noparallel;
alter index CR_ORDER_NUMBER_INDEX noparallel;
alter index INV_ITEM_SK_INDEX noparallel;
alter index INV_DATE_SK_INDEX noparallel;
alter index INV_WAREHOUSE_SK_INDEX noparallel;
alter index CP_START_DATE_SK_INDEX noparallel;
alter index CP_END_DATE_SK_INDEX noparallel;
alter index WP_CREATION_DATE_SK_INDEX noparallel;
alter index WP_ACCESS_DATE_SK_INDEX noparallel;
alter index WP_CUSTOMER_SK_INDEX noparallel;
alter index SR_RETURNED_DATE_SK_INDEX noparallel;
alter index SR_RETURN_TIME_SK_INDEX noparallel;
alter index SR_ITEM_SK noparallel;
alter index SR_CUSTOMER_SK_INDEX noparallel;
alter index SR_CDEMO_SK_INDEX noparallel;
alter index SR_HDEMO_SK_INDEX noparallel;
alter index SR_ADDR_SK_INDEX noparallel;
alter index SR_STORE_SK_INDEX noparallel;
alter index SR_REASON_SK_INDEX noparallel;
alter index SR_TICKET_NUMBER_INDEX noparallel;
alter index C_CURRENT_CDEMO_SK_INDEX noparallel;
alter index C_CURRENT_HDEMO_SK_INDEX noparallel;
alter index C_CURRENT_ADDR_SK_INDEX noparallel;
alter index C_FIRST_SHIPTO_DATE_SK_INDEX noparallel;
alter index C_FIRST_SALES_DATE_SK_INDEX noparallel;

